using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System;
using System.Collections.Generic;

using System.IO;
using System.Reflection.Metadata;

namespace tp_final
{
    internal class enums
    {
    }
}
///////////////////////////////////////////////////////////
//  eProducto.cs
//  Implementation of the Enumeration eProducto
//  Generated by Enterprise Architect
//  Created on:      01-Nov-2022 5:59:00 AM
//  Original author: laraf
///////////////////////////////////////////////////////////

public enum eProducto : int
{

    Licuadora,
    Exprimidor,
    Rallador,
    Tostadora,
    Cafetera,
    MolinilloDeCafe,
    Cocina,
    Calefon,
    Termotanque,
    Lavarropas,
    Secarropas,
    Heladera,
    Microondas,
    Freezer,
    Computadoras,
    Impresoras,
    PequeniosAccesorios,
    Televisor

}//end eProducto

public enum eTipoEntrega : int
{

    Express,
    Normal,
    Diferido

}//end eTipoEntrega



/// <summary>
/// Liniers = 0; Vicente_Lopez, San_Isidro, General_San_Martin, Tres_de_Febrero,
/// Moron, La_Matanza, Lomas_de_Zamora, Lanus, Avellaneda, Comuna1, Comuna2,
/// Comuna3, Comuna4, Comuna5, Comuna6, Comuna7, Comuna8, Comuna9, Comuna10,
/// Comuna11, Comuna12, Comuna13, Comuna14, Comuna15
/// </summary>
public enum eZona : int
{

    Liniers,
    VicenteLopez,
    SanIsidro,
    GeneralSanMartin,
    TresDeFebrero,
    Moron,
    LaMatanza,
    LomasDeZamora,
    Lanus,
    Avellaneda,
    Comuna1,
    Comuna2,
    Comuna3,
    Comuna4,
    Comuna5,
    Comuna6,
    Comuna7,
    Comuna8,
    Comuna9,
    Comuna10,
    Comuna11,
    Comuna12,
    Comuna13,
    Comuna14,
    Comuna15

}//end eZona

public struct dimensiones
{
   public float alto;
   public float ancho;
   public float largo;
   public float peso;
}
